### ISSUE TITLE
M table calculations should be cached in elasticsearch

### ISSUE THREAD

**Issue by purbon** [fair-search/fairsearch-elasticsearch-plugin#9]
M table calculations are expensive to compute, for this reason, they should be cached internally in elasticsearch.

We should be caching this as documents in an internal special index.

For this we should create an special REST endpoint, together with it's related transport actions. This endpoint will be responsible for:

- [ ] Trigger the calculation of a new M Table based on the given set of parameters.
- [ ] Delete an stored m table.
- [ ] Trigger an update of an already calculated M table.

## Endpoints draft proposal

```json
POST _fairness_table/_create
{
   "model" : {
          "name": "foo",
          "proportion": 3,
          "alpha": 0.1,
          "table": [[1,2,3],[4,5,6]] 
    }
}
the _table_ param is optional, if not set the table execution will calculated on demand, otherwise will be gotten from the parameter.

we use the same, but with PUT to trigger an update.

```
GET _fairness_table/foo
```
```
DELETE _fairness_table/foo
```


depends on: #1
